// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Checkpoint struct {
	ID          int64  `json:"id"`
	SessionID   int64  `json:"session_id"`
	WorkspaceID string `json:"workspace_id"`
	Label       string `json:"label"`
	Kind        string `json:"kind"`
	Messages    string `json:"messages"`
	MsgCount    int64  `json:"msg_count"`
	CreatedAt   string `json:"created_at"`
}

type CheckpointLegacyClaim struct {
	ClaimKey     string `json:"claim_key"`
	WorkspaceID  string `json:"workspace_id"`
	SessionID    int64  `json:"session_id"`
	ClaimedCount int64  `json:"claimed_count"`
	CreatedAt    string `json:"created_at"`
}

type ControlItem struct {
	ID             int64  `json:"id"`
	ItemID         string `json:"item_id"`
	IdempotencyKey string `json:"idempotency_key"`
	SessionID      int64  `json:"session_id"`
	WorkspaceID    string `json:"workspace_id"`
	Kind           string `json:"kind"`
	GoalID         string `json:"goal_id"`
	ExecutionID    string `json:"execution_id"`
	TurnID         string `json:"turn_id"`
	ExternalID     string `json:"external_id"`
	Summary        string `json:"summary"`
	PayloadJson    string `json:"payload_json"`
	PayloadSha256  string `json:"payload_sha256"`
	CreatedAt      string `json:"created_at"`
	RecordedAt     string `json:"recorded_at"`
}

type ControlResolution struct {
	ID             int64  `json:"id"`
	ResolutionID   string `json:"resolution_id"`
	IdempotencyKey string `json:"idempotency_key"`
	ItemID         string `json:"item_id"`
	SessionID      int64  `json:"session_id"`
	WorkspaceID    string `json:"workspace_id"`
	Outcome        string `json:"outcome"`
	EvidenceJson   string `json:"evidence_json"`
	EvidenceSha256 string `json:"evidence_sha256"`
	ResolvedBy     string `json:"resolved_by"`
	Detail         string `json:"detail"`
	ResolvedAt     string `json:"resolved_at"`
	RecordedAt     string `json:"recorded_at"`
}

type ExecutionEvent struct {
	ID              int64  `json:"id"`
	SessionID       int64  `json:"session_id"`
	WorkspaceID     string `json:"workspace_id"`
	RunID           string `json:"run_id"`
	TurnID          string `json:"turn_id"`
	ExecutionID     string `json:"execution_id"`
	IdempotencyKey  string `json:"idempotency_key"`
	ProviderCallID  string `json:"provider_call_id"`
	CanonicalCallID string `json:"canonical_call_id"`
	Iteration       int64  `json:"iteration"`
	Ordinal         int64  `json:"ordinal"`
	ToolName        string `json:"tool_name"`
	Kind            string `json:"kind"`
	EffectClass     string `json:"effect_class"`
	EventType       string `json:"event_type"`
	Approval        string `json:"approval"`
	ArgumentsSha256 string `json:"arguments_sha256"`
	ResultSha256    string `json:"result_sha256"`
	ResultReceipt   string `json:"result_receipt"`
	Detail          string `json:"detail"`
	OccurredAt      string `json:"occurred_at"`
	RecordedAt      string `json:"recorded_at"`
}

type FileChange struct {
	ID        int64  `json:"id"`
	SessionID int64  `json:"session_id"`
	FilePath  string `json:"file_path"`
	ToolName  string `json:"tool_name"`
	Added     int64  `json:"added"`
	Removed   int64  `json:"removed"`
	CreatedAt string `json:"created_at"`
}

type SQLCReconciliationGroup struct {
	ID                   int64  `json:"id"`
	GroupItemID          string `json:"group_item_id"`
	IdempotencyKey       string `json:"idempotency_key"`
	SessionID            int64  `json:"session_id"`
	WorkspaceID          string `json:"workspace_id"`
	GoalID               string `json:"goal_id"`
	TurnID               string `json:"turn_id"`
	BlockerReference     string `json:"blocker_reference"`
	SnapshotCursor       int64  `json:"snapshot_cursor"`
	GoalSnapshotSha256   string `json:"goal_snapshot_sha256"`
	MemberSetSha256      string `json:"member_set_sha256"`
	ExecutionMemberCount int64  `json:"execution_member_count"`
	PayloadJson          string `json:"payload_json"`
	PayloadSha256        string `json:"payload_sha256"`
	CreatedAt            string `json:"created_at"`
	RecordedAt           string `json:"recorded_at"`
}

type SQLCReconciliationGroupMember struct {
	ID                int64  `json:"id"`
	GroupItemID       string `json:"group_item_id"`
	ControlItemID     string `json:"control_item_id"`
	ExecutionID       string `json:"execution_id"`
	TurnID            string `json:"turn_id"`
	EventID           int64  `json:"event_id"`
	EventType         string `json:"event_type"`
	EffectClass       string `json:"effect_class"`
	EventSha256       string `json:"event_sha256"`
	ItemPayloadSha256 string `json:"item_payload_sha256"`
	RecordedAt        string `json:"recorded_at"`
}

type SQLCReconciliationGroupResolution struct {
	ID             int64  `json:"id"`
	ResolutionID   string `json:"resolution_id"`
	IdempotencyKey string `json:"idempotency_key"`
	GroupItemID    string `json:"group_item_id"`
	SessionID      int64  `json:"session_id"`
	WorkspaceID    string `json:"workspace_id"`
	EvidenceJson   string `json:"evidence_json"`
	EvidenceSha256 string `json:"evidence_sha256"`
	ResolvedBy     string `json:"resolved_by"`
	ResolvedAt     string `json:"resolved_at"`
	RecordedAt     string `json:"recorded_at"`
}

type Session struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Model       string `json:"model"`
	Mode        string `json:"mode"`
	WorkspaceID string `json:"workspace_id"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	PublicID    string `json:"public_id"`
}

type SessionMessage struct {
	ID        int64  `json:"id"`
	SessionID int64  `json:"session_id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	ToolName  string `json:"tool_name"`
	ToolArgs  string `json:"tool_args"`
	IsError   int64  `json:"is_error"`
	Thinking  string `json:"thinking"`
	CreatedAt string `json:"created_at"`
}

type SessionState struct {
	SessionID int64  `json:"session_id"`
	StateJson string `json:"state_json"`
	Revision  int64  `json:"revision"`
	UpdatedAt string `json:"updated_at"`
}

type TokenStat struct {
	ID           int64  `json:"id"`
	SessionID    int64  `json:"session_id"`
	Turn         int64  `json:"turn"`
	EvalCount    int64  `json:"eval_count"`
	PromptTokens int64  `json:"prompt_tokens"`
	Model        string `json:"model"`
	CreatedAt    string `json:"created_at"`
}

type ToolPermission struct {
	ID        int64  `json:"id"`
	ToolName  string `json:"tool_name"`
	Policy    string `json:"policy"`
	UpdatedAt string `json:"updated_at"`
}
